name = "CBFV"
uuid = "e079e57c-70e8-4f61-a09b-990e8be4fed3"
authors = ["Stefan Bringuier <stefanbringuier@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"

[compat]
DataFrames = "1"
ProgressBars = "1"
CSV = "0.10"
julia = "1.6.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
