name = "CBFV"
uuid = "e079e57c-70e8-4f61-a09b-990e8be4fed3"
authors = ["Stefan Bringuier <stefanbringuier@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
